/*
 * Copyright © 2026 jsonwebtoken.io
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.jsonwebtoken.impl.security

import io.jsonwebtoken.impl.RfcTests
import io.jsonwebtoken.impl.lang.Bytes
import io.jsonwebtoken.io.Encoders
import io.jsonwebtoken.security.*
import org.junit.Test

import java.security.KeyPair
import java.security.PrivateKey
import java.security.PublicKey
import java.security.Signature

import static org.junit.Assert.*

/**
 * Tests for the {@code AKP} JWK key type defined by
 * <a href="https://www.rfc-editor.org/rfc/rfc9964.html">RFC 9964</a>.
 */
class AkpJwksTest {

    /**
     * Returns true if ML-DSA is available on the current runtime, either natively (JDK 24+) or via BouncyCastle.
     */
    private static boolean available() {
        try {
            MlDsaAlgorithm.ML_DSA_44.keyPair().build()
            return true
        } catch (Throwable ignored) {
            return false
        }
    }

    private static KeyPair keyPair(MlDsaAlgorithm alg) {
        return alg.keyPair().build()
    }

    /**
     * Returns a keypair whose private key encoding is guaranteed to retain the RFC 9964-required seed.  A pair
     * generated by the runtime's default path may not (JDK 24 through 26 encode an expanded private key only), so
     * this uses BouncyCastle, whose encoding contains both the seed and the expanded key.
     */
    private static KeyPair seedRetainingKeyPair(MlDsaAlgorithm alg) {
        return alg.keyPair().provider(Providers.findBouncyCastle()).build()
    }

    @Test
    void testPublicJwkRoundtripAllParameterSets() {
        if (!available()) return
        for (MlDsaAlgorithm alg : MlDsaAlgorithm.VALUES) {
            def pub = keyPair(alg).getPublic()

            def jwk = Jwks.builder().key(pub).build() as AkpPublicJwk
            assertEquals 'AKP', jwk.getType()
            assertEquals alg.getId(), jwk.getAlgorithm()
            assertEquals alg.getPublicKeyByteLength(), (jwk.get('pub') as String).decodeBase64Url().length
            assertEquals pub, jwk.toKey()

            // serialize and parse back:
            String json = Jwks.json(jwk)
            def parsed = Jwks.parser().build().parse(json)
            assertEquals jwk, parsed
            assertEquals pub, parsed.toKey()
        }
    }

    @Test
    void testPrivateJwkRoundtrip() {
        if (!available()) return
        for (MlDsaAlgorithm alg : MlDsaAlgorithm.VALUES) {
            // Build a private key from a known seed so the test does not depend on whether the runtime's default
            // provider retains the seed in generated keys (JDK 24 through 26 do not):
            byte[] seed = Bytes.random(MlDsaAlgorithm.SEED_LENGTH)
            PrivateKey priv = alg.toPrivateKey(seed, null)
            PublicKey pub = keyPair(alg).getPublic() // any matching-parameter-set public key for structure checks

            def jwk = Jwks.builder().key(priv).publicKey(pub).build() as AkpPrivateJwk
            assertEquals 'AKP', jwk.getType()
            assertEquals alg.getId(), jwk.getAlgorithm()
            // RFC 9964 Section 6 requires 'priv' to be the 32-byte seed:
            assertArrayEquals seed, jwk.get(DefaultAkpPrivateJwk.PRIV) as byte[]

            assertTrue jwk.toString().contains('<redacted>') // secret values are not printed

            def parsed = Jwks.parser().build().parse(Jwks.UNSAFE_JSON(jwk)) as AkpPrivateJwk
            assertEquals jwk, parsed
            assertEquals jwk.toPublicJwk(), parsed.toPublicJwk()
        }
    }

    /**
     * Asserts that a key parsed from an AKP JWK can actually produce an ML-DSA signature.
     */
    @Test
    void testParsedKeysSignAndVerify() {
        if (!available()) return
        def alg = MlDsaAlgorithm.ML_DSA_65
        byte[] seed = Bytes.random(MlDsaAlgorithm.SEED_LENGTH)
        PrivateKey priv = alg.toPrivateKey(seed, null)
        def pub = keyPair(alg).getPublic()
        def jwk = Jwks.builder().key(priv).publicKey(pub).build()
        def parsed = Jwks.parser().build().parse(Jwks.UNSAFE_JSON(jwk)) as AkpPrivateJwk

        byte[] data = 'hello ML-DSA'.getBytes('UTF-8')
        def key = parsed.toKey() as PrivateKey
        def signer
        try {
            signer = Signature.getInstance(alg.getId())
            signer.initSign(key)
        } catch (Exception ignored) { // the parsed key may come from a different provider than the JCA default
            signer = Signature.getInstance(alg.getId(), Providers.findBouncyCastle())
            signer.initSign(key)
        }
        signer.update(data)
        byte[] sig = signer.sign()
        assertTrue sig.length > 0
    }

    @Test
    void testPublicJsonParse() {
        if (!available()) return
        def alg = MlDsaAlgorithm.ML_DSA_44
        def pub = keyPair(alg).getPublic()
        String encoded = Encoders.BASE64URL.encode(alg.getPublicKeyMaterial(pub))

        String json = RfcTests.stripws("""
        {
           "kty": "AKP",
           "alg": "${alg.getId()}",
           "pub": "$encoded"
        }""")

        def jwk = Jwks.parser().build().parse(json) as AkpPublicJwk
        assertEquals 'AKP', jwk.getType()
        assertEquals alg.getId(), jwk.getAlgorithm()
        assertEquals encoded, jwk.get('pub')
        assertEquals pub, jwk.toKey()
    }

    @Test
    void testMissingAlg() {
        if (!available()) return
        def alg = MlDsaAlgorithm.ML_DSA_44
        String encoded = Encoders.BASE64URL.encode(alg.getPublicKeyMaterial(keyPair(alg).getPublic()))
        String json = RfcTests.stripws("""{"kty":"AKP","pub":"$encoded"}""")
        try {
            Jwks.parser().build().parse(json)
            fail()
        } catch (MalformedKeyException expected) {
            assertTrue expected.getMessage().contains("'alg'")
        }
    }

    @Test
    void testUnrecognizedAlg() {
        String json = RfcTests.stripws("""{"kty":"AKP","alg":"ML-KEM-768","pub":"AQID"}""")
        try {
            Jwks.parser().build().parse(json)
            fail()
        } catch (UnsupportedKeyException expected) {
            assertTrue expected.getMessage().contains('ML-KEM-768')
        }
    }

    @Test
    void testInvalidPubLength() {
        String json = RfcTests.stripws("""{"kty":"AKP","alg":"ML-DSA-44","pub":"AQID"}""")
        try {
            Jwks.parser().build().parse(json)
            fail()
        } catch (InvalidKeyException expected) {
            assertTrue expected.getMessage().contains('1312')
        }
    }

    @Test
    void testUnrecognizedKty() {
        String json = RfcTests.stripws("""{"kty":"XYZ","pub":"AQID"}""")
        try {
            Jwks.parser().build().parse(json)
            fail()
        } catch (UnsupportedKeyException expected) {
            assertTrue expected.getMessage().contains('XYZ')
        }
    }

    @Test
    void testPrivateKeyWithoutPublicKey() {
        if (!available()) return
        PrivateKey priv = MlDsaAlgorithm.ML_DSA_44.toPrivateKey(Bytes.random(MlDsaAlgorithm.SEED_LENGTH), null)
        try {
            Jwks.builder().key(priv).build()
            fail()
        } catch (InvalidKeyException expected) {
            assertTrue expected.getMessage().contains('publicKey')
        }
    }

    @Test
    void testMismatchedPublicKeyParameterSet() {
        if (!available()) return
        PrivateKey priv = MlDsaAlgorithm.ML_DSA_44.toPrivateKey(Bytes.random(MlDsaAlgorithm.SEED_LENGTH), null)
        PublicKey pub = keyPair(MlDsaAlgorithm.ML_DSA_65).getPublic()
        try {
            Jwks.builder().akpKey(priv).publicKey(pub).build()
            fail()
        } catch (InvalidKeyException expected) {
            assertTrue expected.getMessage().contains('does not match')
        }
    }

    @Test
    void testBuilderWithMatchingExplicitAlg() {
        if (!available()) return
        def pub = keyPair(MlDsaAlgorithm.ML_DSA_44).getPublic()
        def jwk = Jwks.builder().key(pub).algorithm('ML-DSA-44').build() as AkpPublicJwk
        assertEquals 'ML-DSA-44', jwk.getAlgorithm()
    }

    @Test
    void testBuilderWithMismatchedAlg() {
        if (!available()) return
        def pub = keyPair(MlDsaAlgorithm.ML_DSA_44).getPublic()
        try {
            Jwks.builder().key(pub).algorithm('ML-DSA-65').build()
            fail()
        } catch (InvalidKeyException expected) {
            assertTrue expected.getMessage().contains("does not equal the specified key's ML-DSA parameter set")
        }
    }

    @Test
    void testPublicBuilderPrivateKeyChaining() {
        if (!available()) return
        def pair = seedRetainingKeyPair(MlDsaAlgorithm.ML_DSA_65)
        def jwk = Jwks.builder().akpKey(pair.getPublic()).privateKey(pair.getPrivate()).build() as AkpPrivateJwk
        assertEquals 'AKP', jwk.getType()
        assertEquals pair.getPublic(), jwk.toPublicJwk().toKey()
    }

    @Test
    void testAkpKeyPair() {
        if (!available()) return
        def alg = MlDsaAlgorithm.ML_DSA_44
        def pair = seedRetainingKeyPair(alg)
        byte[] seed = alg.getSeed(pair.getPrivate())
        assertEquals MlDsaAlgorithm.SEED_LENGTH, seed.length
        def jwk = Jwks.builder().akpKeyPair(pair).build() as AkpPrivateJwk
        assertEquals alg.getId(), jwk.getAlgorithm()
        assertEquals pair.getPublic(), jwk.toPublicJwk().toKey()
    }

    @Test
    void testAkpKeyPairWithNonMlDsaKeys() {
        def pair = new KeyPair(new TestPublicKey(algorithm: 'RSA'), new TestPrivateKey(algorithm: 'RSA'))
        try {
            Jwks.builder().akpKeyPair(pair)
            fail()
        } catch (InvalidKeyException expected) {
            assertTrue expected.getMessage().startsWith('Unrecognized ML-DSA key')
        }
    }

    @Test
    void testGenericKeyDispatchWithUnresolvableMlDsaPublicKey() {
        def key = new TestPublicKey(algorithm: 'ML-DSA') // ML-DSA by name, but no encoding to resolve the set
        try {
            Jwks.builder().key((PublicKey) key)
            fail()
        } catch (UnsupportedKeyException expected) {
            assertTrue expected.getMessage().startsWith('There is no builder that supports specified key')
        }
    }

    @Test
    void testGenericKeyDispatchWithUnresolvableMlDsaPrivateKey() {
        def key = new TestPrivateKey(algorithm: 'ML-DSA')
        try {
            Jwks.builder().key((PrivateKey) key)
            fail()
        } catch (UnsupportedKeyException expected) {
            assertTrue expected.getMessage().startsWith('There is no builder that supports specified key')
        }
    }

    @Test
    void testIdFromThumbprint() {
        if (!available()) return
        def pair = seedRetainingKeyPair(MlDsaAlgorithm.ML_DSA_65)
        def jwk = Jwks.builder().akpKeyPair(pair).idFromThumbprint().build() as AkpPrivateJwk
        assertNotNull jwk.getId()
        // the private JWK id must equal the one computed for the public JWK per RFC 7638 Section 3.2.1:
        assertEquals jwk.toPublicJwk().getId(), jwk.getId()
    }

    @Test
    void testThumbprintUsesRfc9964Members() {
        if (!available()) return
        def alg = MlDsaAlgorithm.ML_DSA_44
        def pub = keyPair(alg).getPublic()
        def jwk = Jwks.builder().key(pub).build()
        // RFC 9964 requires the AKP thumbprint to be computed over alg, kty and pub, in that order:
        assertEquals(['alg', 'kty', 'pub'], DefaultAkpPublicJwk.THUMBPRINT_PARAMS.collect { it.getId() })
        assertNotNull jwk.thumbprint()
    }

    @Test
    void testEqualsAndHashCode() {
        if (!available()) return
        def pub44 = keyPair(MlDsaAlgorithm.ML_DSA_44).getPublic()
        def jwk44a = Jwks.builder().key(pub44).build()
        def jwk44b = Jwks.builder().key(pub44).build()
        assertEquals jwk44a, jwk44b
        assertEquals jwk44a.hashCode(), jwk44b.hashCode()

        def jwk65 = Jwks.builder().key(keyPair(MlDsaAlgorithm.ML_DSA_65).getPublic()).build()
        assertNotEquals jwk44a, jwk65

        def ecJwk = Jwks.builder().key(TestKeys.ES256.pair.public).build()
        assertNotEquals jwk44a, ecJwk

        byte[] seed = Bytes.random(MlDsaAlgorithm.SEED_LENGTH)
        def priv44 = MlDsaAlgorithm.ML_DSA_44.toPrivateKey(seed, null)
        def privJwk1 = Jwks.builder().akpKey(priv44).publicKey(pub44).build()
        def privJwk2 = Jwks.builder().akpKey(priv44).publicKey(pub44).build()
        assertEquals privJwk1, privJwk2
        assertEquals privJwk1.hashCode(), privJwk2.hashCode()
        assertNotEquals privJwk1, jwk44a // private vs public

        def rsaPrivJwk = Jwks.builder().key(TestKeys.RS256.pair.private).build()
        assertNotEquals privJwk1, rsaPrivJwk
    }
}
